name: CI

on:
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up PureScript toolchain
      uses: purescript-contrib/setup-purescript@main

    - name: test
      run: spago test
